meta_product_name: "Ambulant App"
meta_title: "Ambulant App | Encontre o ambulante que está passando no seu bairro e entre em contato com ele!"
meta_description: "O site Ambulant App é um marketplace que une consumidores a vendedores ambulantes. No Ambulant, consumidores logados podem visualizar em tempo real os vendedores que estão próximos, saber quais produtos vendem e entrar em contato com eles para combinar a venda."
meta_image: "ambulant_banner.png" # in `app/assets/images/`
